### ISSUE TITLE
Loss of several admin functionalities after installing moodle-theme_shoelace

### ISSUE THREAD

**Issue by arodriguez5789** [gjb2048/moodle-theme_shoelace#2]
After installing shoelace version 2.8.1 today, all the links in everything under Advanced Features is broken/disconnected.  Runnning Moodle 2.8.1+, Build 20141205.

**Comment by gjb2048** [comment]
Hi Anthony,

Any news?

Cheers,

Gareth

**Comment by arodriguez5789** [comment]
Hello Gareth,

Thanks for following up. I really like your shoelace theme, but I still haven't been able to correct the link issue which I'm wondering if it is nothing more than a permission issue.  I'm building this moodle project for a very good friend's not-for-profit organization and he especially liked the clean, simple look of the theme for ease of use for those who would be subscribing to his learning and training website.  

I'm not sure where to begin, especially as you have not been able to replicate the issue, but I do believe that eventually I'll figure it out with a little more proficiency in troubleshooting the application and theme.  

Thanks, again, for your follow-up. I may use one of your other themes for another project that I'm also working on.  

Regards,

Anthony Rodriguez

**Comment by gjb2048** [comment]
Hi Anthony,

Thank you for letting me know.  I've been cloning Shoelace for some other projects and not had any issues.

Have you checked the PHP error log?  Any issues on the console?  Any possible conflicts with other contributed plugins?  Does Shoelace work on your WAMP / LAMP stack on a clean separate install of Moodle?

Cheers,

Gareth

**Comment by gjb2048** [comment]
P.S. I think those arrows do an AJAX call to get more information for the navigation tree.  So might be a place to start investigating.

**Comment by gjb2048** [comment]
Hi Anthony,

Any progress with this or I'll close the issue.

Gareth

**Comment by arodriguez5789** [comment]
Hello Gareth,

Please, close the issue as I will be managing the site a little differently now. I do appreciate your work and may employ you shortly for a project that I am working on, as I do like your themes. 

Regards,

Anthony Rodriguez

**Comment by gjb2048** [comment]
Hi Anthony,

Thanks for letting me know.

Cheers,

Gareth
